package wit.fcl.bookmark;


/*
 THIS FILE IS AUTOMATICALLY GENERATED.
 DEVELOPER: FCL
 2015-02-02 01:49:36
 */

public class AnnosElement {
	private String name;
	private Integer flags;
	private Integer expires;
	private String value;

	public void init() {
		name = "Places/SmartBookmark";
		flags = 0;
		expires = 4;
		value = "RecentlyBookmarked";
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return this.name;
	}

	public void setFlags(Integer flags) {
		this.flags = flags;
	}

	public Integer getFlags() {
		return this.flags;
	}

	public void setExpires(Integer expires) {
		this.expires = expires;
	}

	public Integer getExpires() {
		return this.expires;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getValue() {
		return this.value;
	}

}
