package wit.fcl.bookmark;


import java.util.List;

/*
 THIS FILE IS AUTOMATICALLY GENERATED.
 DEVELOPER: FCL
 2015-02-02 02:28:02
 */

public class FirefoxBookmarkBean {
	private String guid;
	private String title;
	private Integer index;
	private Long dateAdded;
	private Long lastModified;
	private Integer id;
	private String type;
	private String root;
	private List<ChildrenElement> children;

	public void init() {
		guid = "1x0TuYoOkSEv";
		title = "";
		index = 0;
		dateAdded = 1376875321850000L;
		lastModified = 1376899848952000L;
		id = 1;
		type = "text/x-moz-place-container";
		root = "placesRoot";
		children = null;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getTitle() {
		return this.title;
	}

	public void setIndex(Integer index) {
		this.index = index;
	}

	public Integer getIndex() {
		return this.index;
	}

	public void setDateAdded(Long dateAdded) {
		this.dateAdded = dateAdded;
	}

	public Long getDateAdded() {
		return this.dateAdded;
	}

	public void setLastModified(Long lastModified) {
		this.lastModified = lastModified;
	}

	public Long getLastModified() {
		return this.lastModified;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return this.id;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getType() {
		return this.type;
	}

	public void setRoot(String root) {
		this.root = root;
	}

	public String getRoot() {
		return this.root;
	}

	public void setChildren(List<ChildrenElement> children) {
		this.children = children;
	}

	public List<ChildrenElement> getChildren() {
		return this.children;
	}

}
